sudo: false

language: "python"

branches:
  only:
    - master

matrix:
  include:
    - python: 3.7-dev
      env: TOXENV=py37
    - python: pypy
      env: TOXENV=pypy

install:
  - pip install -U pip setuptools wheel
  - pip install tox codecov

script:
  - tox

after_success:
  - codecov

notifications:
  email: false
  irc:
     channels: "chat.freenode.net#divmod"
     template:
       - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
     use_notice: true
